# Generated by Django 3.2.7 on 2021-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.TextField(max_length=24, null=True),
        ),
    ]
